### ISSUE TITLE
Verify the checksum of the upstream packages, and verify if the checksum is gpg-signed

### ISSUE THREAD

**Issue by mscherer** [release-monitoring/anitya#191]
Idea from @olasd 

It would be quite nifty to see if there is a checksum and verify it, and also verify that it is still correctly signed. So any attack ( as it happened in the past ) would be caught faster.

**Comment by pypingou** [comment]
Could you expand a little on how this would work? (how would we know the checksum for example?)

**Comment by mscherer** [comment]
By downloading it, as they are often shipped at the same place as the tarball. I suspect there is a finite variation of way you can name it ( like MD5SUMS, etc ), and the same go for signature. 

Example: http://www.postgresql.org/ftp/source/v9.2.0/  there is a .md5 file.

The packager could list the gpg key, and we will just check against it. The idea is to check the key didn't change from the past, rather than doing the full verification of identity.

Bonus point, we could start to rank upstream by some metrics on "being serious by using more than md5, using a proper gpg key", ie assess usage ( so checksum + signature ), and then later people using strong enough keys and checksum ( like what qualys did for SSL ).

**Comment by genodeftest** [comment]
MD5? I'd say MD5 is so broken, it doesn't even count as checksum anymore.
