### ISSUE TITLE
Report all new releases

### ISSUE THREAD

**Issue by ctubbsii** [release-monitoring/anitya#269]
Currently, this system only reports versions of they are newer than the latest version. However, I'd like to track all new releases.

Example: version 1.6.X is packaged for Fedora, but upstream supports two release lines, 1.6.X and 1.7.X. I'd like to update to the latest supported 1.6 version, but not necessarily jump to 1.7 versions.

**Comment by gregswift** [comment]
+1

the monitor doesn't seem to catch newer reasons even after that.

It shows 2.12.0 as the latest because 2.11.4 was after that but 2.12.1 and 2.13.0 has come out since.

https://release-monitoring.org/project/6605/
https://support.sonatype.com/hc/en-us/articles/213464368-Sonatype-Nexus-Release-Notes-Index

**Comment by pypingou** [comment]
@gregswift well, in your case the regex has become invalid after the release 2.12.0
check ``Sonatype Nexus ([\d\.]*) Release Notes`` at https://support.sonatype.com/hc/en-us/articles/213464368-Sonatype-Nexus-Release-Notes-Index

**Comment by gregswift** [comment]
d'oh i was looking at the wrong line. thanks for catching that

**Comment by gregswift** [comment]
So test check shows 2.13.0, but running full check still throws the same log message and doesn't grab new versions.

**Comment by pypingou** [comment]
Seems to be there, maybe the UI change wasn't clear enough :(

**Comment by gregswift** [comment]
did a hard refresh of the page and now its there. sorry for hijacking. thank you

**Comment by carlwgeorge** [comment]
Tracking different version "streams" is even more relevant now that we have [modularity](https://docs.pagure.org/modularity/).

There are also third party repos such as [IUS](https://ius.io) that contain packages tied to an upstream branch (i.e. redis32u will always be redis 3.2.x).  I would love to use anitya to track releases for IUS, but it's not feasible until it can notify me of new releases that are lower than the absolute latest.

**Comment by jeremycline** [comment]
I'd definitely accept a PR that fixes this. I'm not on the Fedora infrastructure apps team anymore so the amount of time I have to devote to development is limited, but I'll see about making it a weekend project if no one else gets to it.

**Comment by Zlopez** [comment]
Implemented in #641

**Comment by carlwgeorge** [comment]
Excellent, thanks for implementing this.

I do have a follow up question, let me know if it makes sense as a new issue or if we can discuss it here.  Is there a way to have a distribution mapping be restricted to only some versions?  For example, [mariadb](https://release-monitoring.org/project/1887/) is now detecting versions for all upstream branches.  I have mappings for mariadb100u and mariadb101u for the IUS project.  I would like to limit fedmsg announcements for those distribution mappings to certain versions.

* mariadb100u: 10.0.X versions
* mariadb101u: 10.1.X versions

**Comment by Zlopez** [comment]
@carlwgeorge Not in the current state. We plan to have mapping for something similar in https://github.com/fedora-infra/the-new-hotness/issues/230, but the-new-hotness is only working with Fedora packages.

Otherwise this could be done in your consumer of fedmsg messages (I recommend to switch to fedora messaging), just look at the prefix of the version.
