### ISSUE TITLE
Add GitLab backend

### ISSUE THREAD

**Issue by glensc** [release-monitoring/anitya#272]
please add gitlab.com backend support.
sample: https://gitlab.com/gitlab-org/gitlab-ce/tags

**Comment by glensc** [comment]
yeah, gitlab.com hosting is becoming more popular by any day

**Comment by akien-mga** [comment]
I'd also like to see support for a GitLab backend added. If some bug triager or OP could rename the issue to something more verbose, it might be helpful too :) (e.g. "Add GitLab backend").

Here's an example of a GitLab hosted project for which anitya can't currently get the version: https://release-monitoring.org/project/8535/

Note that GitLab is an open source backend which is hosted by various websites, not only the commercial gitlab.com. Here's an alternative for example: http://gitgud.io/
So the GitLab anitya backend should allow specifying a platform different from gitlab.com

Here's the tag structure to get a tarball of a GitLab project (e.g. https://gitlab.com/ballz/ballz/tags/)
`$platform/$user/$repo/repository/archive.$ext?ref=$tag`
e.g. https://gitlab.com/ballz/ballz/repository/archive.tar.bz2?ref=v1.0.3

$ext can be .tar, .tar.gz, .tar.bz2 and .zip, so we just need to pick one.

Alternatively, anitya could maybe just parse the tags overview page and retrieve the highest one, i.e.:
`$platform/$user/$repo/tags/$tag`
e.g. https://gitlab.com/ballz/ballz/tags/v1.0.3

**Comment by glensc** [comment]
IMHO it's better to use API. but anitya maintainers did not want to use API (in GitHub driver) because API access  might get rate limited.

hmm, i can't even see appropriate api call from here:
https://docs.gitlab.com/ce/api/

**Comment by pypingou** [comment]
> anitya maintainers did not want to use API (in GitHub driver) because API access might get rate limited.

For most backend that have an API, anitya is using it, the main exception is github to due its rate limited implementation.

**Comment by Conan-Kudo** [comment]
You'd probably want to use [the GitLab Tags API](https://docs.gitlab.com/ce/api/tags.html) for this. The API call returns a list of all tags/releases for a repository.

**Comment by pypingou** [comment]
That will make writing the plugin quite easy :)

**Comment by nqb** [comment]
+1 for thise feature.

**Comment by Zlopez** [comment]
Gitlab backend added by https://github.com/release-monitoring/anitya/pull/591
