### ISSUE TITLE
admin+fdummy mapped the name of "cucumber-rails" in Fedora to "rubygem-cucumber-core"

### ISSUE THREAD

**Issue by voxik** [release-monitoring/anitya#279]
Not sure how this happened, but it seems that upstream monitoring screwed up for rubygem-cucumber-core, which is freshly imported into Fedora. I got these notifications from FMN:

```
Subject: pkgdb_updater updated: description, upstream_url of rubygem-cucumber-core

pkgdb_updater updated: description, upstream_url of rubygem-cucumber-core
    https://admin.fedoraproject.org/pkgdb/package/rubygem-cucumber-core/
```

```
Subject: admin+fdummy mapped the name of "cucumber-rails" in Fedora to "rubygem-cucumber-core"

admin+fdummy mapped the name of "cucumber-rails" in Fedora to "rubygem-cucumber-core"
    https://release-monitoring.org/project/4317/
```

```
Subject: hotness tried to map rubygem-cucumber-core to an upstream project, but failed:  "None"

hotness tried to map rubygem-cucumber-core to an upstream project, but failed:  "None"
    https://release-monitoring.org/project/4317/
```

But if you check the 4317 project, it is actually project for "cucumber-rails".

Please note that I'm going to clean this mess up manually.

**Comment by voxik** [comment]
Hmm, so I created "cucumber-core" project, but I can't fix the mapping :((


[1] https://release-monitoring.org/project/10454/

**Comment by pypingou** [comment]
> Subject: pkgdb_updater updated: description, upstream_url of rubygem-cucumber-core
> pkgdb_updater updated: description, upstream_url of rubygem-cucumber-core
>    https://admin.fedoraproject.org/pkgdb/package/rubygem-cucumber-core/

This is pkgdb being updated with the info from the spec file (extracted from yum's repo metadata), so this is likely fine and not related to the others.

**Comment by voxik** [comment]
> This is pkgdb being updated with the info from the spec file (extracted from yum's repo metadata), so this is likely fine and not related to the others.

Might not be related, but this probably triggered the another action, since newhotness realized that there is no upstream monitoring setup yet ...

**Comment by pypingou** [comment]
> Might not be related, but this probably triggered the another action, since newhotness realized that there is no upstream monitoring setup yet ...

No I don't think both events were related.


As for the origin, looking at both projects they seem to be using the same homepage:
* https://release-monitoring.org/project/4317/
* https://release-monitoring.org/project/10454/
So indeed, when the-new-hotness tried to find the original project for the package, it found one with the same homepage and thought the project is releasing different tarballs, therefore it mapped the new package to the same project.

I'm not quite sure what we could do to improve here :-s

**Comment by voxik** [comment]
Huh, I don't thing Anitya should decide anything based on upstream URL. The backend should decide if that is independent project or not

**Comment by pypingou** [comment]
Well anity doesn't decide anything, the-new-hotness sees that there is a new package added to pkgdb, gets its homepage and queries anitya with it.
If there is already a project with that homepage, then the-new-hotness adds the package to the project.

**Comment by voxik** [comment]
Another weird message from the series:

```
hotness tried to map rubygem-cucumber-wire to an upstream project, but failed:  "Could not determine backend for http://cucumber.io"
	http://cucumber.io
```

Really, what the new hotness trying to determine from upstream URL is beyon me. Its Fedora package, it has "rubygem-" prefix, the "Source0:" points to rubygem.org ... Why it bothers with "URL"?

**Comment by pypingou** [comment]
Because it's the only stable element we have to figure out if a package is already in anitya or not.

Names are confusing, tarball names aren't in anitya, we could try doing a bunch of per-language case, but I am not sure how robust it would be (more than the present solution? less?).
Something to investigate maybe.

**Comment by jeremycline** [comment]
This needs to get fixed up in the-new-hotness

**Comment by Zlopez** [comment]
Moved to the-new-hotness https://github.com/fedora-infra/the-new-hotness/issues/201
