### ISSUE TITLE
Add check_feed call for hackage

### ISSUE THREAD

**Issue by ralphbean** [release-monitoring/anitya#301]
@lubomir [pointed out](https://github.com/fedora-infra/anitya/pull/300#discussion_r62886561) that just add .rss to the url makes it work like we need.

**Comment by ralphbean** [comment]
(we can probably do this for stackage too?  That thing has two feeds though, for nightly and for 'lts'...)

**Comment by lubomir** [comment]
I don't think watching Stackage is that important. It should just be a curated set of packages from Hackage. As far as I know, there are no packages that would be in Stackage exclusively.

**Comment by pypingou** [comment]
@juhp was the person most interested in stackage

**Comment by juhp** [comment]
We prefer to watch and Stackage LTS because it is more stable than Hackage. (Stackage Nightly is already on ghc-8.0, which we may move to for F26.)

**Comment by Zlopez** [comment]
The check_feed was never used for any backend AFAIK, I removed it from check_service for this reason. We are still using libraries.io consumer to watch for new releases and projects.

I'm closing this, because it's no longer relevant.
