### ISSUE TITLE
Traceback for some CPAN projects updated by cron script

### ISSUE THREAD

**Issue by bkabrda** [release-monitoring/anitya#337]
Hey, so I promise this is the last issue for the cron script with `--check-feed` :smile: 

I'm seeing tracebacks like these from time to time, only for Perl projects, when `anitya_cron.py` is trying to get their versions:

```
ERROR:anitya:AnityaError catched:
Traceback (most recent call last):
  File "/src/anitya/__init__.py", line 75, in check_release
    up_version = backend.get_version(project)
  File "/src/anitya/lib/backends/cpan.py", line 45, in get_version
    return cls.get_ordered_versions(project)[-1]
  File "/src/anitya/lib/backends/__init__.py", line 256, in get_ordered_versions
    vlist = self.get_versions(project)
  File "/src/anitya/lib/backends/cpan.py", line 67, in get_versions
    return get_versions_by_regex(url, regex, project)
  File "/src/anitya/lib/backends/__init__.py", line 316, in get_versions_by_regex
    return get_versions_by_regex_for_text(req, url, regex, project)
  File "/src/anitya/lib/backends/__init__.py", line 350, in get_versions_by_regex_for_text
    'name': project.name, 'url': url, 'regex': regex})
AnityaPluginException: Test-Simple-1.302050: no upstream version found. - http://search.cpan.org/dist/Test-Simple-1.302050/ -  Test-Simple-1.302050(?:[-_]?(?:minsrc|src|source))?[-_]([^-/_\s]+?)(?i)(?:[-_](?:minsrc|src|source|asc))?\.(?:tar|t[bglx]z|tbz2|zip)
Test-Simple-1.302050: no upstream version found. - http://search.cpan.org/dist/Test-Simple-1.302050/ -  Test-Simple-1.302050(?:[-_]?(?:minsrc|src|source))?[-_]([^-/_\s]+?)(?i)(?:[-_](?:minsrc|src|source|asc))?\.(?:tar|t[bglx]z|tbz2|zip)
```

The interesting thing about the above example is, that the cron script actually creates the project as `Test-Simple-1.302050`, IOW it includes the version in project name. I guess this is the reason why checking for new release fails, since there is no project with that name.

(I'm not sure what's the root of the issue and I'm not that interested in Perl support ATM, so I probably won't be working on this in the near future, I just wanted to report the issue to make sure it's tracked)

**Comment by kentfredric** [comment]
This is likely due to `-TRIAL` in the distribution name, which is an indicator to the indexer that this is a "development release"

The search.cpan.org API is also limited in that it only shows "on the current mirrors" releases, so historical releases that are no longer to be installed are invisible, and will likely cause errors.


Cf: Metacpan.org has this:
https://metacpan.org/release/EXODIST/Test-Simple-1.302050-TRIAL

Whereas the equivalent URI from s.c.o is 404'd.

http://search.cpan.org/~exodist/Test-Simple-1.302050-TRIAL/

**Comment by Zlopez** [comment]
`--check-feed` was removed and the cron job was transformed to service #754 .
