### ISSUE TITLE
add test regexp to edit project view

### ISSUE THREAD

**Issue by glensc** [release-monitoring/anitya#342]
currently at some point there appears "Test check" and "Full check" buttons to project view:
https://release-monitoring.org/project/236/

but would be nice to have the "Test check" button also in edit view:
https://release-monitoring.org/project/236/edit

so i could test changing backend without saving over current setup. for example in this particular project i wanted to test whether actual launchpad backend works, and if it didn't i could stay with current "custom" backend

**Comment by Zlopez** [comment]
Duplicate of https://github.com/release-monitoring/anitya/issues/491
