### ISSUE TITLE
GitHub's heretical `v` version prefix

### ISSUE THREAD

**Issue by akien-mga** [release-monitoring/anitya#374]
Behind a provocative title, a proposal: how about automatically stripping the optional `v` version prefix some people use in their tags on GitHub (as GH itself advises to do)?

Currently in the database we have a mix of entries with `v` defined as prefix to ignore, and others without it. Having this unnecessary prefix makes it harder to compare the "normal" version with the one parsed by anitya.

I'd propose that we do one of those, or both:
- Define a policy about this prefix: should it be kept (no `v` prefix added manually in the backend), or should it be added manually for all relevant projects using the GH backend and such prefixes (lot of work)?
- Enhance the GH backend to automatically strip this optional `v` prefix when identified as such (i.e. the regex should match `v` + "normal" version number, and not `v.*`, so `v0.2.1` would become `0.2.1` but `version3` would stay untouched.

WDYT?

**Comment by akien-mga** [comment]
Note that this "clever left-stripping" should be similar to what GitHub itself does: if you download https://github.com/orga/project/archive/v0.2.1.tar.gz, you will get a folder named `project-0.2.1` and not `project-v0.2.1`.

**Comment by jeremycline** [comment]
I think I would be okay stripping all ``v`` from any string that matches a "normal" version string when the v is gone. The version comparing under the hood already does that, I think, so it seems good to be consistent. It also seems like that would be the preferred behavior in 99% of all projects. 

I wonder if there should be a "Really, please don't mess with my version string" checkbox or if that would complicate the matter and defeat the whole purpose.

**Comment by akien-mga** [comment]
Bumping that as implementing it would really make [Mageia's new versions report](https://www.espelida.com/files/check_anitya.html) more accurate if we could get rid of the 50% of false positives from GitHub.

I could try to propose a patch, though I'm not sure yet how to deploy anitya myself to test the change :)

**Comment by jeremycline** [comment]
@akien-mga the current Ansible role sets everything up for you, and you can use Vagrant to set up a VM and run Ansible. It even grabs the latest backup of the production database so you have projects to play with. There's some basic documentation [here](https://anitya.readthedocs.io/en/latest/contributing.html#development-environment).

**Comment by akien-mga** [comment]
Thanks, I'll give this a try after FOSDEM :)

**Comment by jirutka** [comment]
@akien-mga Mageia always use version number in upstream's format? In Alpine Linux, we normalise it into Gentoo versioning format. When I was working on integration with Anitya, I wrote a lib that tries to convert given version number into that format and also strips "v" and possibly other prefixes: github.com/jirutka/gversion.lua

**Comment by jeremycline** [comment]
As part of #470, I made it so any parsed version [will strip a leading 'v' if it's present](https://github.com/release-monitoring/anitya/pull/470/files#diff-4d367669374d0343eee13cdeebe3ac9bR74) _after_ any defined prefix is removed.

This applies to all projects, not just to GitHub, since it's a pretty wide-spread practice. Is that satisfactory for everyone?

**Comment by sebix** [comment]
I think this can be closed

**Comment by akien-mga** [comment]
Yeah I think it's working fine now. Thanks @jeremycline!
