### ISSUE TITLE
Refactor files/anitya_cron.py into the main package

### ISSUE THREAD

**Issue by jeremycline** [release-monitoring/anitya#383]
It'd be good to have this functionality as part of the main package and to add unit tests for it.

- [ ] Move it into the main package

- [ ] Add an entry point for it in setup.py

**Comment by edvm** [comment]
I'll fix this @jeremycline  :+1:

**Comment by jeremycline** [comment]
@edvm great, ping me here or in IRC if you have questions

**Comment by jeremycline** [comment]
Via IRC
> I'm not sure which is a good place to move https://github.com/fedora-infra/anitya/blob/master/files/anitya_cron.py ... maybe to a file 'conjobs.py' at https://github.com/fedora-infra/anitya/  ?

What I have in mind is moving it inside the [Python package](https://github.com/fedora-infra/anitya/tree/master/anitya). It might be good to add it as a sub-package (called ``cli`` perhaps) and then later we can me the other Python scripts (like createdb.py) there as well.

I did something similar with FMN's createdb.py script: https://github.com/fedora-infra/fmn/pull/160

**Comment by Zlopez** [comment]
This is done in #754
