### ISSUE TITLE
Explore consuming the libraries.io "firehose" API

### ISSUE THREAD

**Issue by ncoghlan** [release-monitoring/anitya#403]
@andrew (creator of @LibrariesIO) pointed out that it has an under-documented "firehose" API that a client can access in order to receive notifications of every new release that libraries.io detects: http://librariesio.github.io/firehose-stream/

That API could offer a useful way of integrating libraries.io not only into release-monitoring.org, but into the fedmsg ecosystem in general.

**Comment by andrew** [comment]
The code that runs the firehose is here: https://github.com/librariesio/firehose (a tiny node.js server sent event app) and some examples of using it in the browser here: https://github.com/librariesio/firehose-stream

Every time Libraries.io finds a new version of a package it's emitted, there's no real state to it but could also provide an rss equivelant if that's easier to integrate

**Comment by jeremycline** [comment]
Neat! Consuming the SSE feed should be fairly simple. 

I like the suggestion of bringing the libraries.io feed into fedmsg so I wonder if the best approach is to add a simple libraryio2fedmsg consumer like [we have to Bugzilla, for example](https://github.com/fedora-infra/bugzilla2fedmsg/) and then add a fedmsg consumer to Anitya. Anitya _could_ consume the SSE feed directly and then publish them to fedmsg, but I like the separation of concerns.

**Comment by pypingou** [comment]
We could just have anitya be that libraryio2fedmsg and make it run a small service publishing the info on both bus

**Comment by ncoghlan** [comment]
The nice part about a separate service is that it wouldn't even need a database or authentication - it could be an entirely stateless component that just needed configuration settings for the URL to query and the bus endpoint to publish messages to.

That way if *all* someone wanted was a fedmsg bridge for libraries.io, then they wouldn't need to run a full Anitya instance and the associated persistent data store.

**Comment by jeremycline** [comment]
I got bored over the weekend and made a little class that turns [any SSE feed into fedmsgs](https://github.com/fedora-infra/sse2fedmsg), so all we need to do in Anitya is consume those messages.

**Comment by ktdreyer** [comment]
Does libraries.io poll at the same interval Anitya does? I'm trying to understand whether it would be simpler to listen to libraries.io events or Anitya events for upstream release monitoring.

**Comment by Zlopez** [comment]
@ktdreyer The Anitya is currently checking for releases every hour, but this will probably change in the future when cronjob, that is currently doing this work, will be changed to service.
Not sure how often does libraries.io is checking for new releases, maybe @andrew can answer your question.

**Comment by ktdreyer** [comment]
Thanks @Zlopez . I've also asked about this at https://github.com/librariesio/firehose/issues/280
