### ISSUE TITLE
Github backend always raises "no upstream version found"

### ISSUE THREAD

**Issue by mattiaverga** [release-monitoring/anitya#412]
Seems that Github backend always raises "no upstream version found" in the logs even if it successfully founds versions.
For example: https://release-monitoring.org/project/1499/
The "failed to update" projects list is full of this: https://release-monitoring.org/projects/updates/failed

**Comment by pypingou** [comment]
https://release-monitoring.org/project/1499/ shows "Version retrieved correctly" for me, maybe a transient error?

**Comment by mattiaverga** [comment]
Did you see "Version retrieved correctly" just after opening the webpage, or after manually run check version?
When I opened the webpage I got again "no upstream version found" in the logs window, after editing the project and manually run check version I now have "Version retrieved correctly".
Maybe the error is generated when the automatic check version is run?

If you look in Projects -> Failed to update menu you can see that there are a lot (all?) of projects with Github backend that have the same error in the logs.

**Comment by akien-mga** [comment]
I've seen this too on a number of projects since a few weeks.

**Comment by pypingou** [comment]
I was (and still, just checked it) seeing it by just accessing the link you provided above.

One of the issue with the GitHub backend is that many people seem to not be using tags and thus we do not find the versions.

**Comment by mattiaverga** [comment]
> I was (and still, just checked it) seeing it by just accessing the link you provided above.

Strange, last time I've entered the page yesterday (after the manual check) I saw "Version retrieved correctly", but now entering the page shows me again "no upstream version found"
![relmon](https://cloud.githubusercontent.com/assets/17218209/22255226/fe3b338a-e256-11e6-9d8a-cedcfa5af641.png)

> One of the issue with the GitHub backend is that many people seem to not be using tags and thus we do not find the versions.

Yes, I'm aware of that, but many projects seems like partitionmanager, the "latest versions" list is populated, but the logs window shows "no upstream version found"

**Comment by Zlopez** [comment]
Should be fixed by https://github.com/release-monitoring/anitya/pull/582

If not, than the project doesn't tagging releases.
