### ISSUE TITLE
Idea: move to dedicated release-monitoring GitHub org?

### ISSUE THREAD

**Issue by ncoghlan** [release-monitoring/anitya#422]
I just claimed https://github.com/release-monitoring as an organization name to match release-monitoring.org and invited @pypingou and @jeremycline to join as organisers

The context is a discussion I had with @puiterwijk regarding the scope names for OIDC permissions: https://fedoraproject.org/wiki/Infrastructure/Authentication#release-monitoring.org

"release-monitoring.org" is used there in the sense of "the upstream project that maintains the Anitya software" rather than as "a particular deployment of Anitya", and I think that would be clearer if "release-monitoring" as also the GitHub org name.

Separating Anitya out to its own org may also make it a little easier to encourage cross-distro collaboration (although the design of OIDC means it's likely going to be tricky for us to avoid requiring that folks updating the main instance have a FAS account)

**Comment by jeremycline** [comment]
I don't have any issue with this. @pypingou, what do you think?

**Comment by pypingou** [comment]
It's fine with me :)
(I already accepted the invitation :))

**Comment by ncoghlan** [comment]
Cool - if you one of you initiates the transfer from this end, any of us should be able to accept it at the far end :)

**Comment by jeremycline** [comment]
Tada!

Although now I don't seem to have write privileges to the repository. I'm not sure if it takes a few minutes for GitHub to sort itself out, or if the roles in the organization need updating.

**Comment by ncoghlan** [comment]
I didn't have the org permissions right for you and @pypingou - turns out folks invited to the org are only members by default, which is enough to create new repos, and hence accept project transfers, but not enough to do anything else.

You're both org owners now, so any of us should be able to fix any remaining permissions issues that come up.

**Comment by pypingou** [comment]
Thanks for that :)
