### ISSUE TITLE
Make 'tox' work with VCS references in requirements.txt

### ISSUE THREAD

**Issue by ncoghlan** [release-monitoring/anitya#426]
Similar to https://github.com/coala/coala-bears/issues/1161, running tox on https://github.com/fedora-infra/anitya/pull/401 currently gives the following error:

    error in anitya setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'+https:/'"

This is due to that PR currently depending on the fix for https://github.com/puiterwijk/flask-oidc/issues/12 (which hasn't been officially released yet).

**Comment by ncoghlan** [comment]
A fix for this is included in https://github.com/fedora-infra/anitya/pull/401 as that's where the problem came up.

**Comment by jeremycline** [comment]
As #401 is merged, I'm closing this as fixed :smile:
