### ISSUE TITLE
OIDC: Support client token generation with the live web service

### ISSUE THREAD

**Issue by ncoghlan** [release-monitoring/anitya#442]
Follow-up to PR #401:

The initial version of the v2 REST API supports client registration in the test suite, but doesn't provide a workflow to enable client token generation when accessing the live web service.

The latter is going to be necessary in order for the OpenID Connect support to be useful in maintaining and updating the upstream/downstream project mappings on release-monitoring.org.

**Comment by Zlopez** [comment]
I'm closing this because PR was already merged.
