### ISSUE TITLE
Remodel the "logs" table

### ISSUE THREAD

**Issue by jeremycline** [release-monitoring/anitya#444]
Anitya has a [logs](https://github.com/release-monitoring/anitya/blob/master/anitya/lib/model.py#L50) table where it stashes events in the database. There are a couple problems with the current model:

* It doesn't use any database relationships - it has a "projects" column that's just a string, when it could relate to a row in the "projects" table. Ditto for distro.

* It has a "user" column and plenty of other things like fedmsgs reference a user. We might be better served making that a table in truth and relating it to logs and projects.

In addition, the Project model has its own [logs column](https://github.com/release-monitoring/anitya/blob/master/anitya/lib/model.py#L358). This is _very_ confusing. I think we need to drop that particular field and use the (reworked) Log model.

- [ ] Remodel logs

- [ ] Write a migration

**Comment by pypingou** [comment]
> It doesn't use any database relationships - it has a "projects" column that's just a string, when it could relate to a row in the "projects" table. Ditto for distro.

This would need to account for project deletion while we may want to retain the logs (if only to know who deleted it)

> In addition, the Project model has its own logs column. This is very confusing.

One log events happening in the entire instance while the other just provide the log of the last check for update.

**Comment by jeremycline** [comment]
> This would need to account for project deletion while we may want to retain the logs (if only to know who deleted it)

It'll allowed to be null so that shouldn't be a problem.

> One log events happening in the entire instance while the other just provide the log of the last check for update.

It seems nicer to have a history of events related to a project. The log table could have an event column or something and we could have 'update', 'create', 'delete', etc. Then you don't just have the result of the last update, you have all of them. We might want to trim these logs so they don't build up forever, but that's easy.

**Comment by jeremycline** [comment]
I think it'd be good to outline what I want here since I spent some time working on something related to this this morning.

# What I Want
Basically, we have this [log](https://github.com/release-monitoring/anitya/blob/d01541cd17d64f569c7cab6462e3a18b53b6437e/anitya/__init__.py#L145) function that creates these log entries, but it's very manual in that as a developer, you need to just _know_ to call it when modifying something that should be logged.

Instead, we should just use an SQLAlchemy event listener on the [before_commit](http://docs.sqlalchemy.org/en/latest/orm/events.html#sqlalchemy.orm.events.SessionEvents.before_commit) event that generates these log entries based on the contents of ``session.new``, ``session.dirty``, and ``session.deleted``. That way logs are easily, automatically added to transactions and no one has to ever think about them. It also means that adding new logs is dead simple: just modify the event listener.

We can then add an [after_commit](http://docs.sqlalchemy.org/en/latest/orm/events.html#sqlalchemy.orm.events.SessionEvents.after_commit) listener to emit fedmsgs based on the log entries generated in the pre-commit listener. Again, that makes it super simple to add or modify fedmsgs Anitya sends, and you don't have to rely on the developer to remember to call ``log``.

# Why I Can't Have What I Want
First, I tried to hook onto creation/modification events for things like ``Project``, but we don't know who made a specific project - it's logged, but in a human-readable format only (and it doesn't reference the project id, just it's name). We need to know who made the project to send messages like:
```
{
  "source_name": "datanommer", 
  "i": 1, 
  "timestamp": 1488462258.0, 
  "msg_id": "2017-a2bd6d24-c720-4826-b090-e59a166eaf8b", 
  "topic": "org.release-monitoring.prod.anitya.project.add", 
  "source_version": "0.6.5", 
  "msg": {
    "project": {
      "regex": null, 
      "name": "myman", 
      "versions": [], 
      "created_on": 1488462258.0, 
      "version": null, 
      "version_url": null, 
      "updated_on": 1488462258.0, 
      "homepage": "https://sourceforge.net/projects/myman/", 
      "id": 13408, 
      "backend": "Sourceforge"
    }, 
    "message": {
      "project": "myman", 
      "agent": "http://fedoradummy.id.fedoraproject.org/"
    }, 
    "distro": null
  }
}
```
Note the "agent" key.

Sure, we could add a user field to projects, or make a table of users and associate them with projects, and I tried to do that initially, but then you don't know who modified the project when it's update. Besides, that's not really what we want. We want to know who created the project, who modified it, what happened last time we looked up the version, etc.

Here's a rough draft of what I think the models could look like. There are a couple things I don't really like here, but I think it helps to write it all down and think about it a bit:

## User
We create a new table and model for users

### Fields
* name  - the openid of the user

### Relationships

* logs - relates to many log entries

## Log

### Fields

* type - The event type. This would be something like a [ChoiceType](http://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#module-sqlalchemy_utils.types.choice) with options like ``project_create``, ``project_update``, ``project_delete``, ``distro_create``... (maybe it's better to have logs by type? That is, ``project`` logs, ``distro`` logs, ``package`` logs, ``version`` logs, etc)

* created_on - When the event took place

### Relationships
I'm not really crazy about having foreign keys to project, distro, and package that are nullable, but maybe it's not that bad.

* user - One-to-many relationship to a user that was responsible for the event

* project - One-to-many relationship to a project the log was for

* distro - One-to-many relationship to a distro the log was for

* package - One-to-many relationship to a package the log was for


# What We Get

* You can do things like ``project_object.logs`` and see who created it, updated it, etc. rather than manually searching the logs table (where it just has the project name, remember, so projects that share a name get mixed together).

* You can hook onto logs creation events to do things (The only way I can think to do this now with all the information provided by a log entry is to start parsing human-readable strings like " new version: 0.5.0 found for project facon (project id: 4424)." and that's just silly)

Thoughts? I get the feeling I'm maybe re-inventing some wheel here. Maybe there's a better way to do all this.

**Comment by jeremycline** [comment]
I found http://docs.sqlalchemy.org/en/latest/_modules/examples/versioned_history/history_meta.html which seems like (perhaps with some modifications) a good approach if we want to keep a history of activity for  certain models.

**Comment by Zlopez** [comment]
The logs table was already refactored and only log for last release check is now kept. Other history is still preserved in messages we sent.
