### ISSUE TITLE
check_feed for maven backend

### ISSUE THREAD

**Issue by pkajaba** [release-monitoring/anitya#445]
Hello, 

I would like to implement `check_feed` method for maven backend. From my investigation maven does central does not have any endpoint where you can query for new packages.

However there is maven index https://repo.maven.apache.org/maven2/.index/ and tool to manipulate maven index: https://github.com/apache/maven-indexer 

It should be doable this way, however anitya would have to call java program during check_feed for maven. What I want ask is - is something like upstreamable?

**Comment by jeremycline** [comment]
Personally, I think that's upstream-able. I'm sure @ncoghlan and @pypingou have opinions as well, but if they don't object then I'd say go for it.

**Comment by ncoghlan** [comment]
I don't see any problems with adding java dependencies to the environment where anitya-cron runs, so there just needs to be a mechanism for making sure the right dependencies are installed.

**Comment by pypingou** [comment]
Any idea on how the two program would interact? How the java piece would get started and report its results?

**Comment by pkajaba** [comment]
I have almost completed java application can read maven index. 

@pypingou my idea about cooperation is that `check_feed` of maven backend will call java application as sub-command are java application will outputs JSON of recently changed jars inside maven index.
Cron would invoke `check_feed` for maven backed every week (changes of maven index in maven central are published every week) and anitya would store changes inside registry. 
I hope it makes sense.

However there is one thing with which I am struggling to understand. For `pypi` [1] or `npmjs` [2] backend anitya picks just first 40 recent changes. why is that so? 

[1] https://github.com/release-monitoring/anitya/blob/master/anitya/lib/backends/pypi.py#L84
[2] https://github.com/release-monitoring/anitya/blob/master/anitya/lib/backends/npmjs.py#L115

**Comment by Zlopez** [comment]
I removed the check_feed method from cron job #754, because it was not used for anything. So I'm closing this issue.
