### ISSUE TITLE
Merge the two docs directories

### ISSUE THREAD

**Issue by jeremycline** [release-monitoring/anitya#454]
I started a Sphinx project for Anitya so we can use all the nice auto-documentation features it provides. However, there's still a [docs](https://github.com/release-monitoring/anitya/tree/master/anitya/docs) folder within anitya which is used to make (for example) [this page](https://release-monitoring.org/fedmsg). 

These need to be moved into the Sphinx project. We can serve the HTML documentation produced by Sphinx at https://release-monitoring.org/docs/ or something with a simple Apache configuration change. Bodhi [started doing this](https://bodhi.stg.fedoraproject.org/docs/) and it's pretty nice.

**Comment by pypingou** [comment]
Bonus point if we can get a nicer sphinx theme :)

**Comment by jeremycline** [comment]
I'm a big fan of [alabaster](http://alabaster.readthedocs.io/en/latest/) which is the Sphinx default these days.

**Comment by pypingou** [comment]
cool :)
