### ISSUE TITLE
Database snapshot

### ISSUE THREAD

**Issue by onny** [release-monitoring/anitya#455]
Hey,
is there any database snapshot to download for release-monitoring?
Otherwise I have to use the api for a lot of packages :(

Best regards,
Jonas

**Comment by jeremycline** [comment]
Hey @onny,

[There is a database dump](https://infrastructure.fedoraproject.org/infra/db-dumps/anitya.dump.xz) for release-monitoring.org which is created daily. I hope it's useful!

**Comment by yann-morin-1998** [comment]
@jeremycline Nice that there are snapshots, but the last one is from last October...

For the Buildroot project, we're planning on using release-monitoring.org as a
way to track package versions, and so we need to query the DB quite a lot.
This has two drawbacks:
- it is slow on ou: querying the status for our 2500+ packages takes 20+ minutes;
- it is adding more stress to the release-monitoring.org server.

Having a DB dump, either via the official API, or on the side (but still at r-m.o) would
allow for faster querying, and would relieve the r-m.o server.

Would the above help you reconsider?

Buildroot: https://buildroot.org/
WIP on using r-m.o: https://patchwork.ozlabs.org/patch/1019781/

Thank you! :-)

Regards,
Yann E. MORIN.

**Comment by Zlopez** [comment]
@yann-morin-1998 I'm not sure, if the dump of anitya db isn't done manually on request, I will check and let you know.

**Comment by Zlopez** [comment]
@yann-morin-1998 It should be done automatically every day, so something is probably wrong right now.

**Comment by jeremycline** [comment]
@yann-morin-1998 I'm a happy buildroot user, thanks for your work on that!

It looks like the daily database dumps on infrastructure.fedoraproject.org are working again.

Ultimately it'd be nice if the API offered a way to service your queries in a more efficient fashion. While I still worked on the infrastructure team, I started on a v2 HTTP (https://release-monitoring.org/static/docs/api.html#http-api-v2), but it's very basic at the moment. Maybe that could be expanded/improved by @Zlopez.

**Comment by Zlopez** [comment]
@jeremycline I want to look at it in future.

**Comment by yann-morin-1998** [comment]
@jeremycline @Zlopez Thanks for the heads up, and for fixing the daily dumps!

We'll see with @tpetazzoni how we can switch to using either the APIv2 or the dump asap.

Thanks! :-)

(and thanks for the nice comment about Buildroot! :-) )

**Comment by tpetazzoni** [comment]
The database dump isn't very trivial to use, as one need to import it into a PostgreSQL server. Would it be possible to get a dump in JSON, XML, or similar format ?

**Comment by Zlopez** [comment]
@tpetazzoni I'm not the one creating the backups, the database is handled by Fedora Infrastructure team. Could you please create a ticket on https://pagure.io/fedora-infrastructure/issues

**Comment by tpetazzoni** [comment]
Thanks, done at https://pagure.io/fedora-infrastructure/issue/9731. However, I believe what is needed is not really at the database level: it should be Anitya itself that produces some JSON output of its database.

**Comment by Zlopez** [comment]
It depends on what you need, some of the things could be already retrieved by API.

**Comment by tpetazzoni** [comment]
We already query through the API, but as we have 2500+ packages, it requires 2500+ API calls, which is quite slow, and probably hammers a bit the release-monitoring.org server. We also do some analysis with the CVE database provided at nvd.nist.gov/, and this one we download entirely as a JSON blurb, and then we can go all the data analysis locally. It would be very nice if we could do the same with the release-monitoring.org data.

**Comment by Zlopez** [comment]
The APIv2 should allow you to get them all in less calls (depends on the pagination), just filter them by distribution or something similar. See https://anitya.readthedocs.io/en/stable/api.html#http-api-v2

**Comment by tpetazzoni** [comment]
Hm, right, but that only works for packages for which we have a name associated in our distribution ("Buildroot"). Though, we do have such an association for a large number of our packages, so perhaps we could improve the speed somewhat with this, and fallback to the per-package queries for packages that don't have any association in our distribution.

**Comment by Zlopez** [comment]
To associate the packages with distribution will definitely help you with the queries.
