### ISSUE TITLE
Could not edit the mapping of Net-SNMP on net-snmp

### ISSUE THREAD

**Issue by glensc** [release-monitoring/anitya#479]
i (again) filled package name into "distribution" field, and when attempting to fix my mistake, i get such error:

> Could not edit the mapping of Net-SNMP on net-snmp, there is already a package Net-SNMP on pld-linux as part of the project Net-SNMP.

![image](https://cloud.githubusercontent.com/assets/199095/25181555/9a53030a-251a-11e7-928e-51d7773f1bb0.png)

but it's a lie, there is no pld-linux mapping and the link directs to the project i tried to fix
https://release-monitoring.org/project/2062/

![image](https://cloud.githubusercontent.com/assets/199095/25181571/a30eab70-251a-11e7-922c-831335376395.png)

**Comment by jeremycline** [comment]
Thanks for the report!

It looks like there's some [faulty logic in the mapping function](https://github.com/release-monitoring/anitya/blob/master/anitya/lib/__init__.py#L229) where it's checking for an existing mapping, but it's finding itself.

**Comment by glensc** [comment]
[update your link not to use branch in url, use tag or commit to get permalink to source code]

**Comment by Zlopez** [comment]
This should be fixed by #608, there were hanging mappings after the distro, project were deleted.
