### ISSUE TITLE
Default custom regex enhanement

### ISSUE THREAD

**Issue by onny** [release-monitoring/anitya#482]
Hey,
I have a small enhancement for the default regex in Anitya:
```
festival(?:[-_]?(?:minsrc|src|source))?[-_]([^-/_s]+?)(?i)(?:[-_](?:minsrc|src|source|asc|release))?.(?:tar|t[bglx]z|tbz2|zip)
```
I had to append `release` string to the `minsrc|src|source|asc` array for the [festival linux software](https://release-monitoring.org/project/14707/). Maybe we can include this into the default regex in Anitya.

Best regards,
Jonas

**Comment by jeremycline** [comment]
Thanks for the suggestion, onny!

That seems like a pretty simple addition that would improve usability, so I'm for it. I wonder if it would be worth making the default custom regex a setting rather than hard-coding it so updates like that can just be configuration changes...
