### ISSUE TITLE
Can't log in with Launchpad OpenID

### ISSUE THREAD

**Issue by anitsirk** [release-monitoring/anitya#484]
When I click on login -> Other OpenID to log in with my Launchpad OpenID, I'm always returned to the login screen without being logged in. My Launchpad OpenID is  https://launchpad.net/~kris-hoeppner

**Comment by puiterwijk** [comment]
Are you by any chance unchecking fields of personal information to be returned?
If not, could you please try again and add the time (UTC) when you did so, so I can look the attempt up in the logs?
Alternatively, you can come by on IRC on #fedora-apps and we can test there.

**Comment by ncoghlan** [comment]
I was able to successfully log in with https://launchpad.net/~ncoghlan, so this isn't a general problem with Launchpad compatibility. That was granting access to all the requested information, though.

**Comment by anitsirk** [comment]
@puiterwijk just tried again (8:32 PM UTC on 25 April 2017) in Firefox on Ubuntu and no luck.

**Comment by anitsirk** [comment]
@puiterwijk "fixed" the issue by restarting the server. If it happens again, I'll get back in touch on IRC. Thank you.
