### ISSUE TITLE
Include version discovery date

### ISSUE THREAD

**Issue by jeremycline** [release-monitoring/anitya#488]
Requested via an email:

I also have a feature request, in e.g. https://release-monitoring.org/project/8054/

I see:

       Latest version(s):

 * 0.9.2
 * 0.9.1
 * 0.9
 * 0.8.1

Could this be expand to include date, something like this:

       Latest version(s):

 * 0.9.2   2017-04-04
 * 0.9.1   2017-01-01
 * 0.9      2016-10-21
 * 0.8.1   2016-09-20

(dates are just a sample data).

This should be easy enough to add by including a creation date on the ProjectVersion model. It's tough to populate old ProjectVersion fields since I think the only place we could find such information is in the human-readable Log table. It might be possible, but I think it's probably not worth the effort so we could just let the column be nullable and show something like "Unknown" by default.

**Comment by Zlopez** [comment]
This was implemented in https://github.com/release-monitoring/anitya/pull/625. Closing.
