### ISSUE TITLE
libpng tarball distribution has moved

### ISSUE THREAD

**Issue by glennrp** [release-monitoring/anitya#489]
Release-monitoring reports the following:
libpng	ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng10/	custom	1.0.67
libpng	ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng15/	custom	1.5.28
libpng	ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng12/	folder	1.2.57
libpng	http://www.libpng.org/pub/png/libpng.html	GitHub	1.7.0beta87

The new locations are
ftp://ftp-osl.osuosl.org/pub/libpng/src/libpng10/
ftp://ftp-osl.osuosl.org/pub/libpng/src/libpng12/
ftp://ftp-osl.osuosl.org/pub/libpng/src/libpng15/
ftp://ftp-osl.osuosl.org/pub/libpng/src/libpng16/
ftp://ftp-osl.osuosl.org/pub/libpng/src/beta/libpng17/

Also available via https, perhaps preferably, at the same locations:
https://ftp-osl.osuosl.org/pub/libpng/src/libpng10/
https://ftp-osl.osuosl.org/pub/libpng/src/libpng12/
https://ftp-osl.osuosl.org/pub/libpng/src/libpng15/
https://ftp-osl.osuosl.org/pub/libpng/src/libpng16/
https://ftp-osl.osuosl.org/pub/libpng/src/beta/libpng17/

**Comment by jeremycline** [comment]
Thanks for the heads-up!

I've adjusted all the libpng projects in release-monitoring.org except for [this one](https://release-monitoring.org/project/1705/). That project looks to be set up to track the latest release of libpng via the GitHub repository. Does that seem reasonable?

In the short term if someone wants to track the 1.6 stream separately from the 1.7 stream they'll have to make another libpng project. However, it would be nice for Anitya to be able to handle this use-case (one upstream project with several release streams that map to several distribution packages, one per stream). That seems like a related problem to #160.

**Comment by glennrp** [comment]
That's fine.  The main thing I'm trying to do is wean people from
simplesystems.org which is a private system and quite overloaded.

People wanting to track the current development can go to github
and look at the libpng16 or libpng17 branch.

It might be worth adding
https://ftp-osl.osuosl.org/pub/libpng/src/beta/libpng16/   # libpng devel

because that's where "current development" happens, i.e., libpng-1.6.0beta and 1.6.0rc series.

**Comment by glennrp** [comment]
Thanks, that's fine.

It might be worth adding this, which is where libpng-1.6 betas and rc's are
published:
https://ftp-osl.osuosl.org/pub/libpng/src/beta/libpng16/

**Comment by jeremycline** [comment]
Excellent. I went ahead and filed [an issue](https://bugzilla.redhat.com/show_bug.cgi?id=1458040) with the libpng package in Fedora as well so they know about the move as well.

**Comment by glennrp** [comment]
I'd still like very much to have
https://ftp-osl.osuosl.org/pub/libpng/src/libpng16/
on the list for the reasons I mentioned above.  If you
feel that that would be too many versions, then I'd
suggest deleting libpng10 and libpng15 and substituting
libpng16.

**Comment by jeremycline** [comment]
I went ahead and made one for libpng16, although anyone can create projects on https://release-monitoring.org/

**Comment by glennrp** [comment]
Thank you very much.  I was not sure who owned the libpng projects on anitya so did not try to create the libpng16 entry myself.

**Comment by glennrp** [comment]
BTW, what's the significance of "folder" (libpng12) versus "custom" (other libpng versions)?

**Comment by jeremycline** [comment]
The folder backend looks for hrefs that point to a file matching the default regular expression for packages, whereas custom allows you to specify any regular expression you want to find the versions in a page. Since none of the projects use custom regular expressions, they could all use the folder backend.
