### ISSUE TITLE
Deploy a staging Anitya on os.stg.fedoraproject.org

### ISSUE THREAD

**Issue by jeremycline** [release-monitoring/anitya#504]
Currently, there's no stage environment for release-monitoring.org. Additionally, release-monitoring.org currently runs on a RHEL 7 host. It'd be nice if we could deploy it on Fedora-based containers in OpenShift. We can even move to Python 3 as soon as fedmsg has Python 3 support.

To do this, we need to get Anitya containerized. There's already a Dockerfile, but it may need updating.

- Evaluate the existing Dockerfile and make any updates and adjustments necessary for the web frontend

- Investigate cron jobs in OpenShift and if necessary create a Dockerfile for the cron job

- File a [request for resources](https://pagure.io/fedora-infrastructure/issues)

- Get a staging version of https://release-monitoring.org on https://os.stg.fedoraproject.org/

**Comment by jeremycline** [comment]
Request for resources filed: https://pagure.io/fedora-infrastructure/issue/6449

**Comment by abitrolly** [comment]
https://pagure.io/fedora-infrastructure/issue/6449 is closed. It is not clear where it is deployed and how it is accessed.

**Comment by jeremycline** [comment]
It's deployed at https://release-monitoring.app.os.stg.fedoraproject.org/ for the moment. stg.release-monitoring.org would be ideal, but I believe it requires some DNS fiddling and I'm not the person to do that.

**Comment by nqb** [comment]
Database from http://release-monitoring.org and https://release-monitoring.app.os.stg.fedoraproject.org/ differs.
https://release-monitoring.app.os.stg.fedoraproject.org/ has an old database.

**Comment by jeremycline** [comment]
Indeed, staging doesn't automatically sync from prod. The cron job also isn't running at the moment, either.

**Comment by Zlopez** [comment]
All issues mentioned here were now solved on staging.
