### ISSUE TITLE
CRAN backend

### ISSUE THREAD

**Issue by QuLogic** [release-monitoring/anitya#510]
Many R packages are published on CRAN. It would be useful to have a backend that works with it. An additional wrinkle is that R versions tend to include dashes like 1.2-3, but on say Fedora, that gets converted to 1.2.3. I'm not sure how it works out on other distros.

**Comment by pypingou** [comment]
Note that using the same logic we could also support Bioconductor and r-forge, all of which provide a http://bioconductor.org/packages/release/data/bioc/src/contrib/PACKAGES file that can be parsed to get the version.

(URLs for all of these sources can be found in https://pagure.io/r2spec/blob/master/f/repos.cfg and this is the logic I used to retrieve the package's info: https://pagure.io/r2spec/blob/master/f/r2spec/rpackage.py#_37-62)
