### ISSUE TITLE
Duplicate entries for docker-py in Fedora

### ISSUE THREAD

**Issue by TomasTomecek** [release-monitoring/anitya#528]
We renamed package from `python-docker-py` to `python-docker` in Fedora and anitya is now spamming our bugzilla for both names, would it be possible to remove one mapping?

https://release-monitoring.org/project/3847/
https://release-monitoring.org/project/13061/

**Comment by jeremycline** [comment]
Done! Let me know if it still doesn't look right.

**Comment by TomasTomecek** [comment]
Jeremy, you did exactly what I wanted, thank you!
