### ISSUE TITLE
/fedmsg page has "about" title 

### ISSUE THREAD

**Issue by sebix** [release-monitoring/anitya#530]
https://release-monitoring.org/fedmsg is about fedmsg but the html title is the same as for https://release-monitoring.org/about, namely "About - Anitya". It should be something different, e.g. "Fedmsg - Anitya" or so

**Comment by abitrolly** [comment]
I don't understand Anitya link processing at all. `/fedmsg`. 

https://github.com/release-monitoring/anitya/blob/52d01219b58ba6c945a07230920a9f8b01b4cd4b/anitya/ui.py#L58-L62

The handler should redirect to docs page - https://github.com/release-monitoring/anitya/blob/master/docs/user-guide.rst but no, there is some other page instead.

**Comment by pypingou** [comment]
What is in git is not what is deployed, as simple as this :)

**Comment by Zlopez** [comment]
This issue is no longer relevant after release of 0.13.1 to production.
