### ISSUE TITLE
Switch to querying pypi.org instead of pypi.python.org

### ISSUE THREAD

**Issue by ncoghlan** [release-monitoring/anitya#531]
PyPI is in the progress of migrating away from the existing implementation at pypi.python.org to the new implementation at pypi.org.

For Anitya, the core changes for this should be limited to https://github.com/release-monitoring/anitya/edit/master/anitya/lib/backends/pypi.py, where we'll want to:

* switch at least one example URL over to the new site layout
* query the new service for version information
* query the new service for the RSS feed

We'll also want to ensure that the tests continue to cover registering with both the old-style and new-style project URLs.

The notification issue is at https://github.com/pypa/warehouse/issues/2935, so I'll post any question we have there.

**Comment by brainwane** [comment]
I did a quick search and see files like `anitya/files/migrate_wiki.py` and `anitya/anitya/tests/test_flask_api_v2.py` referring to pypi.python.org or pypi.io but *not* pypi.org, so perhaps those are due attention as well? Not sure, as I don't know this codebase.

**Comment by ncoghlan** [comment]
I left some old references in on purpose, since we still want to support *users* entering the legacy URLs out of update (at least for now).

I'm not sure what `migrate_wiki` is about, though.

**Comment by jeremycline** [comment]
I *think* ``migrate_wiki`` was for when projects were manually tracked on a wiki at some point in the distant past. I'm fairly confident we can delete it.

**Comment by pypingou** [comment]
It was used to migrate data from Fedora's wiki into anitya when anitya got created (before that we had a wiki page, a script parsing it and filling bug in bugzilla when there was a new release).
