### ISSUE TITLE
Add support for different version-streams

### ISSUE THREAD

**Issue by sgallagher** [release-monitoring/anitya#547]
Oftentimes, different releases of Fedora/EPEL require us to monitor more than one version stream from an upstream project.

For example, the Node.js project: on EPEL 7, I'd like to have Bugzilla tickets automatically opened against new releases in the Node.js 6.x stream, but on Fedora 28 I'd like to have updates about Node.js 8.x and on Fedora Rawhide I might always want the absolute latest one.

It should be possible on release-monitoring.org to specify multiple expressions that should generate Bugzilla tickets.

**Comment by pypingou** [comment]
That'll more likely be a ticket for the-new-hotness

**Comment by sgallagher** [comment]
https://github.com/fedora-infra/the-new-hotness/issues/191

**Comment by jeremycline** [comment]
I think this really needs to be a couple tickets, actually. Anitya needs to record _all_ new versions it finds, even if they're not "newer" by \<insert version sorting here\>. the-new-hotness needs to map new version x to some stream/dist-git branch and open a pull request.

Ideally we'd be able to automatically make reasonable guesses about what version maps to what branch, but I think that's probably only possible with projects using semantic versions. Whatever you turn the-new-hotness on/off these days would probably be the place to add a map of version x (via regex) to branch y.
