### ISSUE TITLE
Project UI should clearly indicate the source its using to find updates regardless of homepage

### ISSUE THREAD

**Issue by jeremycline** [release-monitoring/anitya#549]
For example, setting a GitHub backend and configuring it to poll the ``ceph/ceph`` GitHub owner/project gives users no indication in the UI that it's looking there if the homepage is set to some other location.

For example: https://release-monitoring.org/project/267/ is polling https://github.com/ceph/ceph/, but a user can't know that without editing the project.

**Comment by nqb** [comment]
+1

Moreover, when you receive notifications through Fedora Apps regarding a new release, you want to read, for example, changelog of new release. 

Currently, you get e-mail like this : 
> A new version of "LimeSurvey" has been detected:  "3.6.3+180416" newer than "3.6.2+180406", packaged as "(nothing)"
>     https://release-monitoring.org/project/17126/

It will be nice to have links like this (here for GitHub backend) on Project UI :

### Latest version(s):
* [3.6.3+180416](https://github.com/LimeSurvey/LimeSurvey/releases/tag/3.6.3%2B180416)

or

### [Latest version(s)](https://github.com/LimeSurvey/LimeSurvey/releases):
* 3.6.3+180416

I think this can solve this issue.

**Comment by nqb** [comment]
@Zlopez : do you think we can fix this issue with new GitHub backend ?

**Comment by Zlopez** [comment]
@nqb: I don't think so, we are checking only tags. We don't have the release information.
Also not every project uses github releases.

However I want to add link to commit in Anitya to each version, see https://github.com/release-monitoring/anitya/issues/590, so you can at least got this in e-mail.

**Comment by nqb** [comment]
Perfect, thanks !

**Comment by Zlopez** [comment]
Implemented by #663. Closing.
