### ISSUE TITLE
search.cpan.org is being replaced by MetaCPAN

### ISSUE THREAD

**Issue by eseyman** [release-monitoring/anitya#558]
According to https://log.perl.org/2018/05/goodbye-search-dot-cpan-dot-org.html, search.cpan.org is being retired and MetaCPAN.org will be the canonical front-end for CPAN.

The anitya CPAN backend makes heavy use of search.cpan.org.
* Urls in http://search.cpan.org/dist/ need to be renamed to https://metacpan.org/release/
* The RSS feed for new upload is now https://metacpan.org/feed/recent

**Comment by jeremycline** [comment]
Thanks for the heads-up!

In addition to what you noted, we'll need a database migration to change all the homepages and such to metacpan.
