### ISSUE TITLE
"Project edited" message when no edits was made

### ISSUE THREAD

**Issue by abitrolly** [release-monitoring/anitya#573]
I did an edit without changes for https://release-monitoring.org/project/13914/ to ping the project. Regex was okay, version retrieved successfully, logs are empty, because no changes were made, but the message on the page still says "Project edited". It could be more explicit that no changes are made.

![image](https://user-images.githubusercontent.com/8781107/43992876-a1e04828-9db7-11e8-8e94-85157e98f363.png)

**Comment by Zlopez** [comment]
@abitrolly 
Shouldn't it be better to not show anything if there was no change done.

**Comment by abitrolly** [comment]
It is better to say that "No changes are made", because people may forget to set fields, or submit different form, or form control may break.

**Comment by Zlopez** [comment]
Ok, I will change that in the Pull request.

**Comment by abitrolly** [comment]
Note that we still need to wait for somebody with commit access to review and merge this PR.
