### ISSUE TITLE
GitHub backend does not see any tags

### ISSUE THREAD

**Issue by AloisMahdal** [release-monitoring/anitya#581]
I just logged in to  https://release-monitoring.org/ (anitya v0.11, at this moment) and added 2 GitHub projects: ymattw/ydiff and naelstrof/slop.  I tried to test them and both end with error:

    From https://release-monitoring.org/:
    Unable to retrieve the latest version from upstream! ERROR: ydiff: no upstream version found. - https://github.com/ymattw/ydiff/tags - class="tag-name">([^<]*)</span

It looks like the error contains pieces of HTML regex; however the regex cannot match; this is how HTML looks now:

    [...]
    <h4 class="flex-auto min-width-0 pr-2 pb-1 commit-title">
      <a href="/ymattw/ydiff/releases/tag/1.1">
        1.1
      </a>
      <span class="hidden-text-expander inline"><button type="button" aria-expanded="false" class="ellipsis-expander js-details-target" aria-label="Toggle commit message">&hellip;</button></span>
    </h4>
    [...]

As I mentioned, the site uses old anitya version, but I haven't found this issue in release notes nor in Issues, so this is probably broken with v0.12 as well.

**Comment by AloisMahdal** [comment]
Needless to say, matching against HTML is rather questionable; especially in case of GitHub it looks like Anitya could do way better by just querying the git repos directly.

**Comment by Heidistein** [comment]
This is also breaking other existing packages (ie phpMyAdmin)

**Comment by Zlopez** [comment]
I'm already started working on implementation of Github API. Hopefully, it will be delivered in next version.

**Comment by cheese1** [comment]
+1

**Comment by Zlopez** [comment]
Github API was already merged. Closing this issue.

**Comment by abitrolly** [comment]
@Zlopez let's close the issue when it is released, because it is not fixed for users who report the problem.

**Comment by abitrolly** [comment]
The error is caused by changed GitHub markup. I can not find `tag-name` in current version of tags page markup - http://web.archive.org/web/20180901082326/https://github.com/sdispater/poetry/tags

In case GitHub API approach fails because of stricter rate limits, just updating the filter may fix the problem.

**Comment by Zlopez** [comment]
Reopening because the new version is still not released.

**Comment by Zlopez** [comment]
Closing after release of 0.13.1 in production.
