### ISSUE TITLE
Fetch only newer version from GitHub using cursor

### ISSUE THREAD

**Issue by Zlopez** [release-monitoring/anitya#589]
After implementation of GitHub API v4 I noticed that there is option to get cursor to last retrieved tag.

This enhancement will help with finding new versions.
Here is the list of things, that needs to be done in Anitya to make this work:

- [x] Retrieve the cursor from GitHub for each tag `anitya/lib/backends/github.py`
- [x] Add new field to ~~version~~ project table in database, which will contain cursor value `anitya/db/models.py`
- [x] Add method to retrieve latest version. This will be same as in #730 
- [x] Use cursor value when checking for new versions `anitya/lib/backends/github.py`

**Comment by nphilipp** [comment]
I'll take this.

**Comment by nphilipp** [comment]
Hmm, while working on #590 I noticed that the cursor values aren't actually stored yet -- unit tests only help of all involved units are tested. :wink:
