### ISSUE TITLE
Add link to commit for GitHub project versions

### ISSUE THREAD

**Issue by Zlopez** [release-monitoring/anitya#590]
After implementation of GitHub API v4 I noticed that there is option to get commitUrl for each tag.

This enhancement will make application more user friendly.
Here is the list of things, that needs to be done in Anitya to make this work:

- [x] Retrieve the commitUrl from GitHub for each tag `anitya/lib/backends/github.py`
- [x] Add new field to ProjectVersion table in database `anitya/db/models.py`
- [x] Add method to save commitUrl to field to github backend `anitya/lib/backends/github.py`
- [x] Modify frontend to use commitUrl when applicable `anitya/templates`

**Comment by Zlopez** [comment]
Thinking about it, maybe it will be better to use link to tag instead of commit, but I'm not sure if GitHub API provides this.

**Comment by nphilipp** [comment]
I've looked into this and all the v4 API seems to offer for direct access is the `commitURL`. We could construct it from the homepage URL ourselves: `https://github.com/<owner>/<repository>/releases/tags/<tagname>` but I'm not sure if this is guaranteed to be stable.

**Comment by Zlopez** [comment]
I will rather go with `commitURL`, which is provided by API.

**Comment by nphilipp** [comment]
#589 is merged
