### ISSUE TITLE
Add sorting by creating date for versions

### ISSUE THREAD

**Issue by Zlopez** [release-monitoring/anitya#593]
Currently the version scheme used by Anitya is sorting the versions by numbers, which is not good in some situation.
I think that it will be better to use date when the version was retrieved. This should solve the problem with showing other than newest version as latest.

**Comment by jeremycline** [comment]
I think it's reasonable to sort by date discovered in the UI, although do keep in mind that some projects maintain multiple major releases at once (e.g. 1.2.2 could come out, then 1.1.4 could come out) which might look odd unless it's obviously sorted by release date.

**Comment by Zlopez** [comment]
Yes, the date of discovering must be shown on the UI. Otherwise it doesn't make sense.

**Comment by Zlopez** [comment]
In the PR #625 I changed the behavior a little. The user can now choose which version scheme he wants to use for the project.
