### ISSUE TITLE
Add rate limit handling

### ISSUE THREAD

**Issue by Zlopez** [release-monitoring/anitya#600]
In current state GitHub API is raising `RateLimit` exception, which is only logged by cronjob.

It will be nice to reschedule the projects check when rate limit is reset. This could be handled by saving all the projects with GitHub backend after exception is raised and run check again only for them.

**Comment by abitrolly** [comment]
A better architecture  is a proper queue/microservice with rate limiting, which flexibly adapts itself to rate limits, and exposes logs and exceptions to public.

But first, I would like to [see stats](https://github.com/sdispater/poetry/tags).

**Comment by Zlopez** [comment]
Yes, this is something I have in my TODO. To better handle the amount of requests. Right now, we are doing check for all the projects in one go, which is not really nice.
I want to divide this load to the whole day. So it will check only a few projects every hour (maybe something more complex later).
The exposition of the logs and exceptions should be done using fedmsg like you proposed in https://github.com/release-monitoring/anitya/issues/574
However, I'm not sure if there is any topic for this right now.

I don't understand the link you sent, this is pointing to tags sdispater/poetry project. How this has to do anything with stats?

**Comment by Zlopez** [comment]
I change the title, because this is not only about GitHub.

**Comment by Zlopez** [comment]
@yarons 
This is not a bad idea, but we have plenty of backends and it;s not good to freeze everything, because one backend reaches rate limit.
In PR #633 I have it implemented for every project separately. Each project is checked after specified time (currently 1 hour) and if rate limit is thrown it is rescheduled to time returned in rate limit exception.

**Comment by yarons** [comment]
I meant freezing the specific backend, not all of them :laughing:.

**Comment by Zlopez** [comment]
I will add this to my TODO list and look at it later. For now it will work on per project basis.

**Comment by yarons** [comment]
So I should be expecting lots of failures ahead :)

**Comment by Zlopez** [comment]
I didn't noticed any ratelimit error with the current number of projects. So I don't think we will hit this anytime soon.

**Comment by yarons** [comment]
![image](https://user-images.githubusercontent.com/406826/48901901-87a76b00-ee5f-11e8-96d8-686504f0d080.png)
Hmmmm sure?

**Comment by Zlopez** [comment]
Oh, last time I checked this, there wasn't any rate limit error.

**Comment by Zlopez** [comment]
It now looks like we are hitting those, but the current PR should still help with this.

**Comment by Zlopez** [comment]
There was one thing I didn't noticed before, how the actual ratelimit cap is handled by GitHub. So I need to change how ratelimit is detected.

**Comment by yarons** [comment]
So in case of rate limit detection per backend it should stop querying once the first failed.

The only problem is that there is no indication so if we're almost at the limit and I'm trying to add another service then when I'll save it and ask for querying I will hit the limit while working with the system so we shouldn't stop at the actual limit but maybe using only 90% of it and keeping some buffer for contributors work.

**Comment by Zlopez** [comment]
This is probably good idea. To not waste whole rate limit at once.

**Comment by Zlopez** [comment]
This issue is already implemented by #678. Closing.
