### ISSUE TITLE
Upstream version not found any more, cpprestsdk, github project

### ISSUE THREAD

**Issue by c72578** [release-monitoring/anitya#609]
Since a couple of weeks, new upstream versions are not found any more by Anitya.

https://release-monitoring.org/project/15531/
Logs:
`cpprestsdk: no upstream version found. - https://github.com/Microsoft/cpprestsdk/tags - class="tag-name">([^<]*)</span`

The last found version was 2.10.3 whereas three versions have been released and tagged in the meantime (v2.10.4, v2.10.5, v2.10.6), which are not shown.
Tested with and without "v" in the Version prefix settings for the project in Anitya.
It is a github project, tags are here:
https://github.com/Microsoft/cpprestsdk/tags

**Comment by Zlopez** [comment]
This is already fixed in version 0.13.0. I hope it will be deployed on https://release-monitoring.org soon.
Right now it is deployed on staging https://stg.release-monitoring.org/.

**Comment by c72578** [comment]
Thanks!
