### ISSUE TITLE
Login into staging using OpenID not possible

### ISSUE THREAD

**Issue by diabonas** [release-monitoring/anitya#616]
It currently seems to be impossible to login into https://stg.release-monitoring.org/ using a custom OpenID provider: after providing the OpenID URL on the [login page](https://stg.release-monitoring.org/login), I am redirected to the [same page](https://stg.release-monitoring.org/login) again without being logged in. In comparison, on https://release-monitoring.org/login, I am first redirected to my OpenID provider to provide username and password, after which I am successfully logged in into Anitya.

I tried different browsers (Firefox, Chromium) and different OpenID providers (https://launchpad.net/~userid, https://openid.stackexchange.com, with and without the `https://`). Even Fedora and Yahoo OpenID (https://userid.id.fedoraproject.org/, https://me.yahoo.com) do not work, so I do not think this is a provider-specific problem.

I do not know whether login into staging might be disabled on purpose, but login using FAS or Yahoo (directly with the corresponding link on the login page instead of using OpenID) seems to work, at least it redirects to the provider login page (I cannot test further, as I do not have an account on one of these services).

**Comment by Zlopez** [comment]
I can confirm this issue with openID, it looks like the redirection is wrong.

However direct login through FAS is working (I'm using this by myself).
