### ISSUE TITLE
about#test-your-regex link is broken

### ISSUE THREAD

**Issue by yarons** [release-monitoring/anitya#628]
I tried the new 0.13.1 version in release monitoring and this link is not working, I tried clicking it on several pages and it didn't work.

An example:
https://release-monitoring.org/project/12636/edit

The link leads to:
https://release-monitoring.org/static/docs/index.html#test-your-regex

Thanks.

**Comment by Zlopez** [comment]
This issue is with whole documentation. It seem's that this wasn't moved from staging to production.

**Comment by Zlopez** [comment]
I fixed the issue with documentation, but this link points to something in old version of the documentation, so this needs to be updated.
