### ISSUE TITLE
Wrong version fetched from GitHub.

### ISSUE THREAD

**Issue by layus** [release-monitoring/anitya#660]
For buck (facebook build system), the oldest version is detected, instead of the most recent one.

See https://release-monitoring.org/project/18388/ where version is 2015.09.10.01 while it should be 2018.10.29.01 as per https://github.com/facebook/buck/releases.

I have not had time to debug this.

**Comment by Zlopez** [comment]
Duplicate of https://github.com/release-monitoring/anitya/issues/642

**Comment by layus** [comment]
Oops, sorry for the duplicate. And thanks for the patch in master :-)
