### ISSUE TITLE
Turn anitya cron job to service

### ISSUE THREAD

**Issue by Zlopez** [release-monitoring/anitya#668]
Current cron job used by Anitya is not very reliable.

So it will be better to turn it into service probably using [twisted](https://twistedmatrix.com/trac/) library. This will make scheduling much easier and we could also add the ability to send e-mail when things are failing.

Here is the list of the features it should have:
- easy scheduling
- notification about high fail rate (probably through e-mail)

**Comment by cheese1** [comment]
just curious: why is it not possible to send mails from cron or because of a failing cron?

**Comment by Zlopez** [comment]
This is probably possible, I just didn't yet look into this option yet.

**Comment by abitrolly** [comment]
Does it make sense to change it to `systemd` job first?

**Comment by Zlopez** [comment]
No, because the systemd units aren't working in containers and the release-monitoring.org is managed in OpenShift.

**Comment by abitrolly** [comment]
In development environment `anitya` is a `systemd` service. It becomes a container in OpenShift? Then there is no logs, no auto-restart unless there is something like Kubernetes managing the lifecycle.

**Comment by Zlopez** [comment]
@abitrolly 
In development the Anitya is only user systemd unit. In OpenShift it is container that is build, deployed and managed by OpenShift. It has auto-restart feature, so if running instance is down, it will try to start it again.
This is the same behavior I want to see with this cron job.

**Comment by abitrolly** [comment]
Does it provide logs, error counter and error messages?

**Comment by Zlopez** [comment]
The logs will be handled the same way as they are now. Saved to the database. Error counter must be implemented, error messages are saved to every project even now as update log.

**Comment by Zlopez** [comment]
Otherwise the log of the container is accessible in OpenShift, I can look at it there.

**Comment by TomasTomecek** [comment]
Did you consider [celery](http://www.celeryproject.org/)?

@abitrolly [OpenShift is Kubernetes](https://www.openshift.com/learn/topics/kubernetes/).

**Comment by Zlopez** [comment]
@TomasTomecek Didn't heard about it. I will give it a try.

**Comment by TomasTomecek** [comment]
[Pagure is using celery to manage tasks](https://pagure.io/pagure/blob/master/f/pagure/lib/tasks.py).

**Comment by Zlopez** [comment]
I looked at it and it's not really usable for Anitya. It needs a broker, which is not necessary in our case, because we have all the information internally available in our current Database.
