### ISSUE TITLE
New version of nextcloud-client not detected

### ISSUE THREAD

**Issue by janvlug** [release-monitoring/anitya#676]
The new [2.5.1 version](https://github.com/nextcloud/desktop/releases/tag/v2.5.1) of nextcloud-client is not visible on this page:
https://release-monitoring.org/project/18381/

**Comment by Zlopez** [comment]
This is probably caused by the ratelimit for github. I'm working on the fix right now and it should part of 0.14.0 release.

**Comment by cheese1** [comment]
probably because release-monitoring.org does not check:

Last check started at (UTC) 2018-12-04 00:10:11 (at the bottom of each page)

#663 
#683 
#684

**Comment by Zlopez** [comment]
This is fixed now. Checking is working again and the version 2.5.1 is retrieved. Closing.
