### ISSUE TITLE
Ecosystem for GNOME projects?

### ISSUE THREAD

**Issue by abitrolly** [release-monitoring/anitya#687]
For [meld](https://release-monitoring.org/project/5520/) what is the purpose of duplicating `Homepage` into non-editable `Ecosystem` field?

![image](https://user-images.githubusercontent.com/8781107/50760212-30772180-1278-11e9-8e51-00ef84759b8b.png)

**Comment by Zlopez** [comment]
We have only few ecosystems right now and these are linked to used backend, if there is no ecosystem for the backend we use the homepage as ecosystem to ensure that the project is unique in the used ecosystem.
The project is considered unique, if there is no project with same name and same ecosystem.

**Comment by abitrolly** [comment]
If there is no ecosystem for GNOME, why expose it at all?

**Comment by Zlopez** [comment]
There is ecosystem for Pypi, Rubygems, Maven, npm and crates, and this information was missing on the project page. So I just made it visible.

**Comment by abitrolly** [comment]
If there is no ecosystem for GNOME, why not just keep this field blank? Why it is needed at all?

**Comment by Zlopez** [comment]
This is only a information for anybody, who wants to see it. Otherwise you need to query database to get this info. In future it will be normalized url to prevent creation of duplicate projects.

**Comment by abitrolly** [comment]
Information is something people understand. I don't understand what is this Ecosystem string in `meld` project description.

**Comment by Zlopez** [comment]
I need to update the documentation than.

**Comment by cheese1** [comment]
i think @abitrolly meant that this ecosystem-field does not make sense on all occasions.
just because npm, pypi, etc. have ecosystems, which is interesting for that projects, does not mean, that we need that information on all projects, especially on projects without ecosystems.

**Comment by Zlopez** [comment]
I understand, but I wanted to make this information public. Because this is used when checking for duplicity. It is filled everytime, so it's not empty even when the project isn't part of any ecosystem. But if this is distracting, I can't hide it for regular users and show it only to admins.

**Comment by jeremycline** [comment]
The fact that we set it to the homepage to enforce a uniqueness constraint is an internal detail that probably isn't interesting to users of the web UI. I think if it's not in the set of "real" ecosystems it should hidden or displayed as "unknown". Probably just hidden.

I think it's fine for it to be part of the API's JSON response (and I think it is) so you can still look at it.

**Comment by Zlopez** [comment]
Ok, I will hide it for users. But I will still let it visible for admins to resolve duplicates more easily.

**Comment by abitrolly** [comment]
Also, the concept of `ecosystem" is much broader than just "package
repository", "community registry" or "official warehouse". People don't
type "rust ecosystem" into DuckDuckGo to find https://crates.io/

**Comment by Zlopez** [comment]
As I said before, I will show it only to admins, because it will be easier to resolve duplicate project. Ecosystem is used in Anitya to make project unique for example in PyPi, because there should be only one project in PyPi with this name.
