### ISSUE TITLE
logs doesn't show all package events

### ISSUE THREAD

**Issue by abitrolly** [release-monitoring/anitya#688]
Logs tab doesn't show my events - I triggered update for `meld` manually by editing page. There are no historic events for my activity, and there are no historic events when I select package.

I expected https://release-monitoring.org/logs?project=meld&from_date= to match https://apps.fedoraproject.org/datagrepper/raw?topic=org.release-monitoring.prod.anitya.project.version.update&package=meld

**Comment by Zlopez** [comment]
Logs aren't working correctly for some time. I refactored the whole logs in this PR #635.
So in 0.14.0, the logs page will look totally different.

**Comment by abitrolly** [comment]
Ok. I will check later. )

**Comment by Zlopez** [comment]
You can check now. It is only showing logs for the projects.
You can still catch any change by consuming fedmsg messages.

**Comment by abitrolly** [comment]
So what is the purpose of this page now?

**Comment by Zlopez** [comment]
Most of the information that were in the logs table is not important for the Anitya. However we are still emitting messages about these events, so this history is still available.
The logs page now contains only check new versions logs, so you can see, where the last update happened and how it ended.
I want to rewrite the projects menu in future, so the logs page will be not needed in the future or I will use it to show the latest versions retrieved.
