### ISSUE TITLE
Cron job is crashing because of project anyterm

### ISSUE THREAD

**Issue by Zlopez** [release-monitoring/anitya#702]
Project anyterm (https://release-monitoring.org/project/8330/) is causing crash of cron job when checking for latest version when it is already retrieved.

This is in the cron job log:
```
sqlalchemy.orm.exc.FlushError: New instance <ProjectVersion at 0x7f27714f3e10> with identity key (<class 'anitya.db.models.ProjectVersion'>, (8330, '1.2.3'), None) conflicts with persistent instance <ProjectVersion at 0x7f2771107f60>
```

This looks like it can't recognize that the version was already retrieved.
[anitya-1547478000-nhgqd.log](https://github.com/release-monitoring/anitya/files/2755778/anitya-1547478000-nhgqd.log)

**Comment by n-cc** [comment]
I'm still running into this on 0.16.1 when querying `api/version/get`:
```
sqlalchemy.orm.exc.FlushError: New instance <ProjectVersion at 0x7f60da315550> with identity key (<class 'anitya.db.models.ProjectVersion'>, (1, '4.1.0'), None) conflicts with persistent instance <ProjectVersion at 0x7f60da2e1fd0>
```
I've confirmed it happens with multiple projects

**Comment by n-cc** [comment]
Not checking `Check latest release on submit` when creating the project seems to fix this issue.

**Comment by Zlopez** [comment]
@n-cc The `Check latest release on submit` doesn't call the cron job, also the cron job is now replaced by service, so this issue shouldn't happen again.

I did a small change in https://github.com/release-monitoring/anitya/pull/786 that should prevent this when using the check.

**Comment by n-cc** [comment]
I just want to confirm that what I'm seeing on 0.16.1 will be fixed:

I'm adding a new project pointing to an internal gitlab repository with two releases, not checking the `Check latest release on submit` box, and then querying the api successfully once, but subsequent queries fail:

```
$ curl --data "id=1" https://anitya.internal/api/version/get
{"backend":"GitLab","created_on":1566486465.0,"ecosystem":"https://gitlab.internal/n-cc/test_anitya","homepage":"https://gitlab.internal/n-cc/test_anitya","id":1,"name":"test_anitya","packages":[],"regex":null,"updated_on":1566486495.0,"version":"1.0.1","version_url":"https://gitlab.internal/n-cc/test_anitya","versions":["1.0.0","1.0.1"]}
$ curl --data "id=1" https://anitya.internal/api/version/get
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
$
```
The error reported on the backend the second time is the `sqlalchemy.orm.exc.FlushError: New instance <ProjectVersion at 0x7f3e4f437c18> with identity key (<class 'anitya.db.models.ProjectVersion'>, (1, '1.0.1'), None) conflicts with persistent instance <ProjectVersion at 0x7f3e4e94ea58>` error.
