### ISSUE TITLE
Can't create projects via API

### ISSUE THREAD

**Issue by ignatenkobrain** [release-monitoring/anitya#710]
```
import asyncio
import aiohttp

async def main():
    pkg = 'rust-flate2-crc'
    url = f'https://release-monitoring.org/api/v2/projects/?ecosystem=crates.io&name={pkg[5:]}'
    auth = aiohttp.BasicAuth('37c61682-fe76-40d3-b5ee-843949fd2fbc', 'MY_TOKEN')
    async with aiohttp.ClientSession(auth=auth) as session:
        async with session.get(url) as resp:
            resp.raise_for_status()
            data = await resp.json()
            if data['total_items'] == 0:
                url = f'https://release-monitoring.org/api/v2/projects/?access_token=MY_TOKEN'
                if pkg != 'rust-flate2-crc':
                    return 'unknown'
                pdata = {'backend': 'crates.io',
                         'homepage': f'https://crates.io/crates/{pkg[5:]}',
                         'name': pkg[5:],
                         'check_release': True}
                async with session.post(url, json=pdata) as resp:
                    print(await resp.json())
                    resp.raise_for_status()
                    print(await resp.json())

if __name__ == '__main__':
    asyncio.run(main())
```

I have this script, however I always get `{'error': 'authentication_required', 'error_description': 'Authentication is required to access this API.'}`.

I would appreciate any help, thanks.

**Comment by Zlopez** [comment]
I don't see anything unusual in your request. I will try it myself and let you know.
Maybe proxy isn't accepting your request.

**Comment by Zlopez** [comment]
I tried this curl request `curl -v --header "Content-Type: application/json" --header "Authorization: token ..." --request POST --data "{}" "<anitya_url>/api/v2/projects/"` on local instance of Anitya without issue. So there is no issue in the code.
I also tried this curl on `release-monitoring.org` and can confirm this issue. It looks like it's something in configuration of the proxies in fedora infrastructure. I will look at it more closely.

**Comment by ignatenkobrain** [comment]
Thanks! Looking forward for a fix ;)

**Comment by ignatenkobrain** [comment]
Just curious, what was the problem?

**Comment by Zlopez** [comment]
The `Authentication` was dropped by some proxy and after addition of `WSGIPassAuthorization On` parameter to Anitya apache configuration the header was correctly passed again.
