### ISSUE TITLE
Javascript error on add project page

### ISSUE THREAD

**Issue by Zlopez** [release-monitoring/anitya#714]
# Issue
Javascript is not working on https://release-monitoring.org/project/new, because of the syntax error in javascript.
```
SyntaxError: unexpected token: identifier
```
This is related to this [line](https://github.com/release-monitoring/anitya/blob/master/anitya/templates/project_new.html#L150), which is missing the `;`. Also it looks like the jinja is removing `\n`, so the next line is actually appended to previous line.

# Solution
Add missing `;`
Add empty line before jinja `if` statement

**Comment by yarons** [comment]
Can we close this? @Zlopez

**Comment by nqb** [comment]
Any workaround to add a project before 0.15 released on release-monitoring.org ?

**Comment by Zlopez** [comment]
Everything should work, but the fields aren't hide or shown when backend is changed.

So you can add new projects, but you'll see more fields than we actually use.

In the meantime you can look at the [staging](https://stg.release-monitoring.org/) instance of Anitya and see what fields are currently used there. The staging is running on 0.15.0 already. Look at the id of the fields.
