### ISSUE TITLE
Corrupted Version check url

### ISSUE THREAD

**Issue by bowlofeggs** [release-monitoring/anitya#732]
I just added dino to release-monitoring.org. I entered https://github.com/dino/dino for the project url and for the version URL (not sure what else makes sense to go there), and it ended up making what looks like a corrupted Version check url:

![screenshot from 2019-02-14 09-55-51](https://user-images.githubusercontent.com/354506/52795069-0404b100-303f-11e9-88ff-01b09851b456.png)

Strangely, it did seem to get the version correctly anyway.

**Comment by Zlopez** [comment]
The GitHub backend is actually using both - homepage and version_url, but this is really strange. I will look at it.

**Comment by Zlopez** [comment]
I looked at https://release-monitoring.org/project/18608/ and the Version check url looks correct. Did you do any changes?

**Comment by bowlofeggs** [comment]
@Zlopez yeah I edited the version_url to be just ```dino/dino```, but the edit form didn't call it a "version_url" and called it "github owner/project" or something like that. Weird that the two forms didn't use the same terminology.

**Comment by Zlopez** [comment]
Yes, this is actually a bug that is already fixed in master. The javascript on the Add project page didn't work.
