### ISSUE TITLE
Handling projects which tag things that aren't releases

### ISSUE THREAD

**Issue by jasontibbitts** [release-monitoring/anitya#734]
So the Slic3r Prusa Edition project (https://release-monitoring.org/project/13388/) has a somewhat bizarre set of tags.  It is a fork of another project but uses a different versioning scheme.  When it pulls from its "upstream" it inherits the tags, which all are numerically much larger.

In addition, there are all sorts of tags made to the repo that don't correspond to real releases.  The actual releases all seem to correspond to tags prefixed with "version_".

You can certainly supply a version prefix to anitya, but this has the effect of simply removing the prefix if it exists.  If it doesn't exist in a tag, that tag is unchanged.  What would make more sense to me is if anitya simply ignored all tags that don't match the version prefix (as well as removing that prefix from the version as normal).  But I suspect but changing the behavior of this would break a number of existing projects.

Another option is to somehow teach anitya how to get actual releases out of github rather than looking at all tags.  This would need to be an option because plenty of projects only make tags and don't designate releases.

**Comment by jasontibbitts** [comment]
Here is a query that gets the relevant information out of the github releases API.  This should technically be enough to parse out a list of tags as we do now, but only those corresponding to releases.  As a bonus, it's possible to identify prereleases, assuming upstream actually specified that properly.  Sadly, this project doesn't.

```
{
  repository(owner: "prusa3d", name: "Slic3r") {
    releases(first: 10, orderBy: {field: CREATED_AT, direction: DESC}) {
      edges {
        cursor
        node {
          name
          tag {
            name
          }
          createdAt
          publishedAt
          isDraft
          isPrerelease
        }
      }
    }
  }
}
```

**Comment by Zlopez** [comment]
This is relevant to this issue #733
