### ISSUE TITLE
Failures during project addition causes distro mapping to be skipped

### ISSUE THREAD

**Issue by QuLogic** [release-monitoring/anitya#735]
If you add a new project and also supply a distro mapping, a version check is performed before adding the mapping. If this version check fails, the distro mapping is not applied.

For example, I just added [cppzmq](https://release-monitoring.org/project/18648/) and it failed to check the version because GitHub rate-limited you. The Fedora distro mapping was then never added. I have since added it manually.

Also, the error message is reported on the "Add project" page making it seem like the project was never added, but it was.

**Comment by Zlopez** [comment]
## Implementation details
Mapping should be saved to the database before doing first check.

Addition of new project could be found here - https://github.com/release-monitoring/anitya/blob/master/anitya/ui.py#L447

This needs change in `create_project` function https://github.com/release-monitoring/anitya/blob/master/anitya/lib/utilities.py#L286
