### ISSUE TITLE
"Edit" form for Distro Mapping forgets the distributions

### ISSUE THREAD

**Issue by ktdreyer** [release-monitoring/anitya#744]
Steps to reproduce:
1. Log into release-monitoring.org
2. Load the python-remoto project here: https://release-monitoring.org/project/3993/
3. Click "Edit" button next to the Fedora distro mapping (this takes me to https://release-monitoring.org/project/3993/map/4034)
4. Look at the HTML form

Actual results:
The form dropdown input says "Alpine"

Expected results:
The form dropdown remembers the value from the database: "Fedora".

**Comment by Zlopez** [comment]
This is a known issue. It falls to default instead of actual distro. It should be easy to fix.
