### ISSUE TITLE
Visiting distro pages throws HTTP 500 errors

### ISSUE THREAD

**Issue by Conan-Kudo** [release-monitoring/anitya#756]
When visiting release-monitoring.org and trying to visit any distro page, the site throws an HTTP 500 error.

E.g.: https://release-monitoring.org/distro/Fedora/

**Comment by Conan-Kudo** [comment]
This was also noticed by @fedya: https://github.com/OpenMandrivaSoftware/rosa-build/issues/28#issuecomment-475990145

**Comment by Zlopez** [comment]
Duplicate of https://github.com/release-monitoring/anitya/issues/709
