### ISSUE TITLE
Fix project homepage for Chafa

### ISSUE THREAD

**Issue by hpjansson** [release-monitoring/anitya#758]
Hi, I noticed that on https://release-monitoring.org/project/17542/, Chafa is listed with its GitHub page as the homepage. It would be nice if it were listed as https://hpjansson.org/chafa/ instead.

The preferred release catalog is https://hpjansson.org/chafa/releases/, but if you'd rather use the GitHub backend for releases, that's fine too.

**Comment by Zlopez** [comment]
Hi, you should be able to edit this by yourself if you log in to Anitya.

**Comment by hpjansson** [comment]
Yeah, working on it.

**Comment by hpjansson** [comment]
Created a FAS acct for myself and updated the info.
