### ISSUE TITLE
If URL is changed, update ecosystem value as well

### ISSUE THREAD

**Issue by eclipseo** [release-monitoring/anitya#764]
Example
https://release-monitoring.org/project/13720/

I modified the .de into .com for the blogspot URL, but ecosystem stayed in .de.
This is problematic because the APIv2 search parameters is using ecosystem to match projects.

**Comment by Zlopez** [comment]
This is definitely a bug. The ecosystem should be either backend related or homepage and if homepage is changed, the ecosystem should be changed too.

**Comment by Zlopez** [comment]
## Implementations details
This should be implemented as a SQLAlchemy event in https://github.com/release-monitoring/anitya/blob/master/anitya/db/events.py

Right now we are only checking if the ecosystem is filled, if not we will fill it. This should be done differently, so every time there is a change to homepage or backend the ecosystem should be also changed.
