### ISSUE TITLE
Complete version reported although custom regex

### ISSUE THREAD

**Issue by rapgro** [release-monitoring/anitya#771]
I'd like to see 0.4 only for any 0.4.xyz release of psi-plus. That could prevent daily entries to rhbz because upstream provides nearly daily a new snapshot release flagged with xyz in the tracked but special github project.

**Comment by Zlopez** [comment]
@rapgro I changed your regex to `(\d+\.\d+)\.(\d)*\.tar\.gz` and now it is only retrieving versions like these:
`1.4.0, 1.4.1, 1.4.2, 1.4.4, 1.4.5, 1.4.7, 1.4.8, 1.4.9`

Is this sufficient for you?

**Comment by Zlopez** [comment]
If you want only `1.4, 1.5` and so on, just update the regex to this `(\d+\.\d+)*\.tar\.gz`

**Comment by rapgro** [comment]
@Zlopez Thanks for your interest. I think it has to be `(\d+\.\d+)\..*\.tar\.gz`, no?

My issue is more about what string gets reported then into rhbz? It seems Anytia takes the whole finding but w/o the prefix tar.gz, although it finds 1.4 it reports 1.4.567 (example) if there's a real snapshot v1.4.567?

**Comment by Zlopez** [comment]
Sorry, I forgot the dot.

The Anitya only takes what is in the group, so everything inside braces. It will than report only `1.4` not the whole version.

**Comment by rapgro** [comment]
Recently, I got:
```
Upstream Release Monitoring 2019-04-17 19:10:00 CEST
Latest upstream release: 1.4.661
Current version/release in rawhide: 1.4.654-2.fc31
```
as in https://bugzilla.redhat.com/show_bug.cgi?id=1699595

**Comment by Zlopez** [comment]
This looks like a bug, because this version isn't even on project's page in Anitya https://release-monitoring.org/project/8411/

For now, doesn't they have any official page where only actual releases are announced?

**Comment by Zlopez** [comment]
What about this repository? https://github.com/psi-plus/main/releases

**Comment by rapgro** [comment]
Indeed, we'd better switch to track the main project instead, to not complicate things more as needed. Thanks for the help. I'll reconfigure Anitya then.

**Comment by rapgro** [comment]
And closing the referenced bug to test if Anitya still complains.

**Comment by Zlopez** [comment]
Glad I could help.

**Comment by rapgro** [comment]
Oh, there's an obsolete entry called psi-dev (already flagged). Please drop this misleading entry. Maybe that gets confused with psi-plus, so a similiar bug as in #770

**Comment by rapgro** [comment]
Yeah, rhbz links to that bad psi-dev entry.
https://bugzilla.redhat.com/show_bug.cgi?id=1699595

**Comment by Zlopez** [comment]
The psi-dev was deleted and the psi-plus package mapping moved to https://release-monitoring.org/project/8411/
