### ISSUE TITLE
Fedrora and Fedora seem to have the same ID internally, typo?

### ISSUE THREAD

**Issue by rapgro** [release-monitoring/anitya#772]
What does 'Fedrora' mean? I fail to switch it to the right distro name 'Fedora' in the mapping for py4j (PyPi). In assumption they both use the same internal ID and it's silly typo.

**Comment by Zlopez** [comment]
This looks like a wrongly typed distribution, this should be now prevented by forcing user to select one distribution from selection.

I need to do some cleaning of the distributions, when I will find some time and the current issue fix with distribution page will be on production.

**Comment by rapgro** [comment]
OK The malicious entry py4j (PyPi) is now gone anyways, due to reason mentioned in #770 .

**Comment by Zlopez** [comment]
The distributions should be cleaned now, I'm closing this issue.
