### ISSUE TITLE
user session lost when submitting new project

### ISSUE THREAD

**Issue by cheese** [release-monitoring/anitya#784]
Steps to reproduce:

1. login release-monitoring with Fedora ID
2. add project
3. submit
Then it shows 'Please log in to access this page.'

version: 0.15.1 on production site

**Comment by Zlopez** [comment]
I tried to reproduce your issue and without any issue, I was still logged in after submitting the project.

**Comment by cheese** [comment]
OK. I tried once again and the issue disappeared.

**Comment by Zlopez** [comment]
It looks like this was only temporary issue, thanks for trying again.
