### ISSUE TITLE
Anitya override a wrong issue in RHBZ

### ISSUE THREAD

**Issue by cheese** [release-monitoring/anitya#785]
A new release report of deepin-terminal from Anitya overrided an ABRT issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1688632
which is private.

![DeepinScreenshot_select-area_20190523152712](https://user-images.githubusercontent.com/303331/58233670-45f47000-7d6f-11e9-9be5-23e8c9b311c9.png)

**Comment by Zlopez** [comment]
I'm moved the issue to the-new-hotness, where it belongs - https://github.com/fedora-infra/the-new-hotness/issues/234
