### ISSUE TITLE
GitHub backend seems to regularly issue 403s

### ISSUE THREAD

**Issue by changlinli** [release-monitoring/anitya#790]
I feel like I've seen this a couple of times, but I'm getting the following:

![image](https://user-images.githubusercontent.com/1762540/59546832-6775f100-8f02-11e9-9925-c2a04821dfd2.png)

Maybe some sort of rate limiting by GitHub? I imagine it's probably transient since so many projects have GitHub backends, but it might be worth looking into so GitHub doesn't block Anitya.

**Comment by changlinli** [comment]
Hmmm... okay that one had other issues (namely the version check URL is incorrect and yet it seems version checks worked anyway which is odd). Here's an example of one with a correct version check URL

![image](https://user-images.githubusercontent.com/1762540/59546947-79f12a00-8f04-11e9-8bcb-0e322af28c06.png)

**Comment by Zlopez** [comment]
This is definitely related to Github ratelimit. I have few feature requests (#589, #733) already created that should help with this.

**Comment by Zlopez** [comment]
From https://developer.github.com/v3/#rate-limiting I noticed that 403 is returned when the limit is already reached, which probably happens a lot. 
We need to handle 403 on GitHub backend as `RateLimitException` instead of `AnityaPluginException`.
