### ISSUE TITLE
RabbitMQ server is not starting in dev environment

### ISSUE THREAD

**Issue by Zlopez** [release-monitoring/anitya#804]
Today I noticed that the RabbitMQ server service is failing in devel environment.

However it could be started by running `sudo /usr/lib/rabbitmq/bin/rabbitmq-server`, which isn't a good workaround because it will not run under `rabbitmq` user.

Without this server running you can't do any action that is sending fedora messaging message.

**Comment by dfateyev** [comment]
@Zlopez hi, any updates on this issue?

**Comment by Zlopez** [comment]
I honestly don't have time to look into it right now. At first glance I don't understand why this isn't working, because it has the same configuration file as Bodhi (https://github.com/fedora-infra/bodhi/blob/develop/devel/ansible/roles/bodhi/tasks/rabbitmq.yml), where the RabbitMQ server is working without issue.
