### ISSUE TITLE
Projects API case sensitivity

### ISSUE THREAD

**Issue by z3ntu** [release-monitoring/anitya#807]
Hi, I'm trying to integrate release-monitoring.org into the postmarketOS (an Alpine-based mobile-focused distro) tools and I've noticed that the API doesn't return results with a different casing than in the request (e.g. `ofoNo` instead of `ofono`). All package names are lowercase, so that's why a package I've added (https://release-monitoring.org/project/21169/) doesn't get found when a search for `0xffff` is done. On the website, searching for a package is case insensitive so it's only in the API.

**Comment by Zlopez** [comment]
This looks like there is different code called when searching on website and through API.
