### ISSUE TITLE
Flush versions of eventlog project

### ISSUE THREAD

**Issue by tpetazzoni** [release-monitoring/anitya#838]
The eventlog project at https://release-monitoring.org/project/14684/ had an incorrect version specification: it was pointing to the syslog-ng version, while eventlog has its own versioning scheme. I have updated the eventlog project to use https://github.com/balabit/eventlog/blob/master/VERSION as a way of getting the version (since there are no git tags available, and listing is not enabled on the tarball page). The correct version 0.12.3 is now detected by Anitya, but all the older and bogus versions from syslog-ng remain.

Could you flush those old incorrect versions ?

Note: let me know if I should use the "Flag" button on the eventlog project instead of reporting a bug here. However, the last time I used the "Flag" button for another project, I never received any feedback, and I don't know if the request was received and taken into account.

**Comment by Zlopez** [comment]
I deleted every version except 0.12.3 and few others that currently I can't delete because of #596
