### ISSUE TITLE
Custom name for PyPi projects

### ISSUE THREAD

**Issue by tpetazzoni** [release-monitoring/anitya#839]
Currently, Anitya uses the "Project Name" to find a match with the PyPi backend. However, sometimes the "Project Name" as known by Anitya may be different from the name known in PyPi.

An example of this is https://release-monitoring.org/project/12002/. It was named python-hiredis in Anitya, because it's the Python binding for Hiredis. However, in PyPi, it's known just as "hiredis", so it couldn't find it. I had to rename the project to "hiredis" in Anitya, but then we now have two "hiredis" projects in Anitya: one for the real Hiredis, and one for this Python binding.

It would have been convenient to keep "python-hiredis" as the project name in Anitya, and tell the PyPi backend that it should search for "hiredis".

**Comment by Zlopez** [comment]
Anitya doesn't have any issue with having projects with same name. They just need to have different homepage.

The `python-` is something that only Fedora is using for python packages, Anitya should only have project name.

**Comment by tpetazzoni** [comment]
OK, so you prefer to have two projects with the same name, good to know. For the record, Buildroot also has python-<something> prefix for all Python packages, but we're going to handle this with mappings. Thanks for your feedback, I'll close this issue.

**Comment by Zlopez** [comment]
No problem, I'm glad this got solved so quickly. :-)
