### ISSUE TITLE
Is Github blocking massive requests from release-monitoring.org ???

### ISSUE THREAD

**Issue by xosevp** [release-monitoring/anitya#840]
Some projects have every day in latest Status: 
`Server responded with status "403": "Forbidden`

For example: https://release-monitoring.org/project/16253/

A manual refresh always works flawlessly.

**Comment by Zlopez** [comment]
This will be fixed by 0.17.0. GitHub returns 403 when ratelimit is reached.

0.17.0 is now in staging and will be deployed on the production soon. Probably next week.
