### ISSUE TITLE
"Internal Server Error" while adding new project

### ISSUE THREAD

**Issue by abitrolly** [release-monitoring/anitya#845]
I am trying to add https://github.com/watchexec/watchexec 

![image](https://user-images.githubusercontent.com/8781107/66707215-a64b7480-ed45-11e9-8b21-d303bc3cb28a.png)

This submission fails with internal server error.

**Comment by abitrolly** [comment]
The project is created https://release-monitoring.org/project/27539/ but it is not fetching versions as expected.

**Comment by abitrolly** [comment]
The error seems to be caused by checking releases on submit.

![image](https://user-images.githubusercontent.com/8781107/66707254-54571e80-ed46-11e9-8236-8e50f96a3d49.png)

**Comment by Zlopez** [comment]
This issue is caused by semantic versioning scheme, I will look at it more closely to find what exactly is causing this, for now you can switch to rpm versioning, which is working.

**Comment by Zlopez** [comment]
I looked at it more closely and now I knew, what is going wrong, you checked, that you want to watch releases, which is fine, but releases aren't using semantic versioning at all, they are using strange names. This is why the check for versions is crashing. 
I will fix the crash and add some nice error message, but I can't do anything with the release names like "1.10.3: a new man", but probably I can use tag from which the version is created instead of name.

**Comment by abitrolly** [comment]
Nice error message will definitely help.

If the interface could query tags without reloading that page, and show which were ok and which were failed - that will be helpful too.

**Comment by Zlopez** [comment]
This will be nice enhancement for Anitya, but it needs changes in how the checking is handled right now. It either recover versions or not. We should do some validations of the retrieved versions before working with it for this to work.

**Comment by abitrolly** [comment]
Does checking occur in a separate job queue and message passed as a result doesn't contain necessary details?

**Comment by Zlopez** [comment]
Checking is done in separate thread on web interface and there is service running as separate pod which does the heavy work in check. The message is sent after new version is discovered when checking.

**Comment by abitrolly** [comment]
Where is the place to modify the message passed from service to web thread, to include the tags discovered?

**Comment by Zlopez** [comment]
There is no message communication between those service and web. Both of them only communicate with database when changing project or adding discovered version.
