### ISSUE TITLE
Distro search is broken

### ISSUE THREAD

**Issue by abitrolly** [release-monitoring/anitya#876]
https://release-monitoring.org/distro/Alpine/search/?pattern=acpi gives 500 Internal Error.

The fix is the same as https://github.com/release-monitoring/anitya/pull/757/files but I am curious why the `distro` relationship doesn't work here?

https://github.com/release-monitoring/anitya/blob/299701f9865f3833cd4eaa4413effa32a5b0996a/anitya/db/models.py#L156-L158

**Comment by abitrolly** [comment]
Should it be `Packages.distro.name` here?

https://github.com/release-monitoring/anitya/blob/299701f9865f3833cd4eaa4413effa32a5b0996a/anitya/db/models.py#L607-L610

**Comment by Zlopez** [comment]
@abitrolly You are right, there should be `Packages.distro_name` in the `search` method.

**Comment by abitrolly** [comment]
@Zlopez why `distro` relationship didn't work?

**Comment by Zlopez** [comment]
I didn't tried it, I just looked at the code and this looks like the cause of the issue. I will try to debug this later.
